### ISSUE TITLE
does not currently working under gcc

### ISSUE THREAD

**Issue by swex** [google/jni-bind#340] opened 2024-09-18 21:12 UTC
trying to use library with `gcc (GCC) 14.2.1 20240801 (Red Hat 14.2.1-1)`
not compiling, most errors comes from the fact that gcc does not allow non namespace template specialization:
```
jni_bind_release.h:1004:13: error: explicit specialization in non-namespace scope ‘struct jni::metaprogramming::Even’
 1004 |   template <>
```

**Comment by jwhpryor** [comment] 2024-09-19 16:39
Unfortunately I had to start with the library being clang only (it might be easy to miss but it's in the project description).

I filed https://github.com/google/jni-bind/issues/4 under the next milestone: https://github.com/google/jni-bind/milestone/3

I would think the main issue would be that I'm using a clang extension in the invocable maps which would need to be worked around: https://github.com/google/jni-bind/blob/f46e3e240818cdb3659bfcc8a08f4a2cfbb20f93/metaprogramming/invocable_map.h#L89

**Comment by jwhpryor** [comment] 2024-09-19 16:41
Closing this as it's duplicate (but do hope to address it one day).

**Closed by jwhpryor** 2024-09-19 16:41 UTC

**Comment by jwhpryor** [comment] 2024-09-19 16:43
Duplicate of https://github.com/google/jni-bind/issues/4.

**Comment by jwhpryor** [comment] 2025-01-21 22:44
FYI this is now supported.
